### ISSUE TITLE
Support for extensions on primitive elements

### ISSUE THREAD

**Issue by eug48** [lantanagroup/FHIR.js#13]
It would be good to add support for these at some point.

i.e.

```xml
 <birthDate id="314159" value="1970-03-30" >
   <extension url="http://example.org/fhir/StructureDefinition/text">
     <valueString value="Easter 1970"/>
   </extension>
 </birthDate>

```

```json
 "birthDate": "1970-03-30",
 "_birthDate": {
   "id": "314159",
   "extension" : [ {
      "url": "http://example.org/fhir/StructureDefinition/text",
      "valueString": "Easter 1970"
   }]
 }
```

(https://www.hl7.org/fhir/json.html#primitive)

Thanks

**Comment by seanmcilvenna** [comment]
You're in luck! I was just starting to investigate doing this last week. However, I'm swamped with other projects right now, so I doubt I will be able to finish doing this in the next couple weeks. BUT, it IS on my radar. I welcome any pull requests you can provide to support this effort :)

**Comment by kylemaclennan** [comment]
Support for the extensions has been reported as a problem for a project I am working on, and before I start digging into it I wanted to confirm you don't already have the code available to support these.

Thanks

**Comment by seanmcilvenna** [comment]
Hi @kylemaclennan ,
Yes. I've got code written for it. I plan to release a new version today that addresses your request.

**Comment by seanmcilvenna** [comment]
Hi @kylemaclennan ,

I have added this functionality and released it to [NPM ](https://www.npmjs.com/package/fhir) as 4.6.0.

Thanks!
