### ISSUE TITLE
Support for STU3

### ISSUE THREAD

**Issue by RafaLop-Mo** [lantanagroup/FHIR.js#17]
Hi guys, in your [README.md](https://github.com/lantanagroup/FHIR.js/blob/master/README.md#key-features) file you mention `Support for multiple FHIR versions (>= STU3)` as a Key Feature, but later in the "FHIR Version" block you mention `If your implementation needs to support a specific FHIR version (as long as it is 3.6.0 or newer)`.

Taking into account that STU3 sequence ends with 3.0.1 as per the [official documentation](http://www.hl7.org/fhir/directory.cfml). Could you please confirm if STU3 is actually supported?

Thank you in advance

**Comment by seanmcilvenna** [comment]
You are correct. There was some odd changes going on with the version numbers of FHIR at some point, and I had thought (at the time) that 3.6.0 represented STU3. You are right, though, that 3.0.1 represents STU3 and the README should be updated to say "as long as it is 3.0.1 or newer".

**Comment by RafaLop-Mo** [comment]
Thank you!
