### ISSUE TITLE
Validation issue on HumanName use property

### ISSUE THREAD

**Issue by kristof-taveirne** [lantanagroup/FHIR.js#18]
Hi,

The valueset http://hl7.org/fhir/ValueSet/name-use has the 'maiden" value as a sub-definition of the value "old". Maiden is Lvl 1 while old is Lvl 0.

`{
            "code": "old",
            "display": "Old",
            "definition": "This name is no longer in use (or was never correct, but retained for records)",
            "concept": [
              {
                "code": "maiden",
                "display": "Name changed for Marriage",
                "definition": "..."
              }
            ]`

validator.js however doesn't seem to check for this value. 

The following bit of FHIR doesn't validate. 
` "name": [
                    {
                        "use": "official",
                        "text": "Walters, Wilma W",
                        "family": [
                            "Walters"
                        ],
                        "given": [
                            "Wilma",
                            "W"
                        ],
                        "period": {
                            "start": "2014-08-04T22:20:44.000Z"
                        }
                    },
                    {
                        "use": "maiden",
                        "text": "Fredricks,",
                        "family": [
                            "Fredricks"
                        ],
                        "period": {
                            "start": "2018-12-20T19:49:51.000Z"
                        }
                    }
                ]`

It returns 
"'[{"location":"Patient.name[1].use","resourceId":"2648007","severity":"error","message":"Code \\"maiden\\" not found in value set"}]',"

A quick fix for the validator is to change valueset.json to have maiden on the same level as old, but that might break when we update to updates of the valueset.

Thank you!

**Comment by caistrop** [comment]
Hi, a fix for this issue would be really useful. I am currently trying to save a Condition resource with a clinicalStatus of "recurrence" which is valid but fails validation as it is not a top level concept in the valuesets.json file (it is a sub-concept of "active")

**Comment by seanmcilvenna** [comment]
Created a release 4.7.9 on NPM to address this. I think this should address the problem you're having. Let me know how it goes!

**Comment by caistrop** [comment]
Hi, release 4.7.9 has solved my issue. Thanks.
