### ISSUE TITLE
Version DSTU2

### ISSUE THREAD

**Issue by jxtiben** [lantanagroup/FHIR.js#19]
Hi,

I'm trying to implement FHIR DSTU2. I'd like to ask you guys why DSTU2 is not supported? Why is the main reason or difference for that?

I ask you that questions because it is possible to download the "FHIR Definitions" of the version 3 and work with this version, so why is not possible to do the same with version2?

**Comment by seanmcilvenna** [comment]
It is theoretically possible that it would work with FHIR DSTU2 definitions... I just haven't done _any_ testing for DSTU2 support. If there were any changes to the StructureDefinition resource between DSTU2 and STU3, it may not work. Feel free to give it a shot and let me know how it goes, though. :)

**Comment by jxtiben** [comment]
Ok, thank you so much. I will try to implement DSTU2 and then I will let you know

**Comment by jxtiben** [comment]
I was not able to implement version 2. The DSTU2 definition file was not possible to be loaded with the provided code. I tried to correct the errors but the among of them was huge. I decided to work with version 3, I just wanna say that I have to correct one line of the code:

I used "parser.parseBundle(newResources);"

instead of "parser.parseResources(newResources);"
