### ISSUE TITLE
Mocha test

### ISSUE THREAD

**Issue by bennetstankidis** [lantanagroup/FHIR.js#2]
The mocha test is not executing all tests.

In package.json there is a script: "test": "./node_modules/.bin/mocha test/*.js" which is not working.
If this script is changed to the following "test": "./node_modules/.bin/mocha test/*" then the mocha tests are executed for me.

Hope this helps!

**Comment by seanmcilvenna** [comment]
Not sure why, but for me, your suggested change did not run *any* tests...
Changing it to "./node_modules/.bin/mocha test/**/*.js" DID run all the tests, though, so I committed that change.

**Comment by seanmcilvenna** [comment]
FYI, I just updated FHIR.js with the latest STU3 schemas and profiles. So it should be compatible with the published version of STU3 now.
