### ISSUE TITLE
xmlToJson broken by #22

### ISSUE THREAD

**Issue by synsteve** [lantanagroup/FHIR.js#23]
Good work on #22 but I think this has broken the xmlToJson code - the _ properties are all empty object now.

**Comment by seanmcilvenna** [comment]
yah, I saw that. I'm working on fixing :/ whoops. rushed too quickly

**Comment by seanmcilvenna** [comment]
ok, fixed. released 4.7.5 to npm and tagged ce3a5daa7536912d6ad525fd4c3d754e79e2a252.

**Comment by seanmcilvenna** [comment]
Found another issue, related to my previous refactor. Sheesh.

**Comment by seanmcilvenna** [comment]
ok. made a final release for the day (v4.7.6) that fixes all issues as of this commit 6345394f0a74bd1e05ea4292ba8f14d254ef0b0e.
oye. have a good evening!
