### ISSUE TITLE
Cannot read property '_properties' of undefined

### ISSUE THREAD

**Issue by awatson1978** [lantanagroup/FHIR.js#6]
Hi,
Trying to parse the Epic sandbox conformance statement from XML to JSON using `fhir.xmlToObj`, and it's returning a `Cannot read property '_properties' of undefined` error.  

I've used this library elsewhere to parse Epic sandbox responses, but I'm not sure I've used it to parse a conformance statement.  Of course, it may simply be the difference between DST2 and v4.  
-aw

![screen shot 2018-03-24 at 9 51 51 am](https://user-images.githubusercontent.com/675910/37865313-0df3fe66-2f49-11e8-911c-73bd5a13a95c.png)

Code that's generating the error: 
```js
import Fhir from 'fhir';

foo(){
  HTTP.get('https://open-ic.epic.com/Argonaut/api/FHIR/Argonaut/metadata', function(error, result){
          if(error){
              console.log('error', error)
          }
          if(result){
              console.log(result.content);
              var parsed = Promise.await(fhir.xmlToObj(result.content));
              self.setState({
                  metadata: EJSON.stringify(parsed, {indent: 2})
              })
        }
      })
}
```

**Comment by awatson1978** [comment]
Maybe we could get some error detection in `node_modules/fhir/toJs.js`?

![screen shot 2018-03-24 at 10 04 46 am](https://user-images.githubusercontent.com/675910/37865467-e0f6b6cc-2f4a-11e8-965f-dd61b97c1ded.png)

**Comment by seanmcilvenna** [comment]
Hi @awatson1978,
I have updated the package to version 4.1.0.
I added an additional error check to determine if the resourceType is valid for the version of FHIR being run.
In your case, you are correct... Conformance is a DSTU2 resource, and this module was recently updated to support the latest version of FHIR (from build.fhir.org, as of about a month ago).
However, previous versions of the module can be used if you need to continue supporting DSTU2 resources. In that case, I would suggest installing/using version 3.3.0.
```
npm install fhir@3.3.0
```
Thanks

**Comment by seanmcilvenna** [comment]
Not, however, that the module's usage is different in 3.3.0 from now.
