### ISSUE TITLE
README.md - example for setting a different FHIR Version references a non-existent function when creating parser.

### ISSUE THREAD

**Issue by NHS-juju** [lantanagroup/FHIR.js#60]
The example shows:
`// Create a parser and parse it using the parser`
`var parser = new ParseConformance(false, FhirVersions.STU3);           // don't load pre-parsed data`
`parser.parseBundle(newValueSets);`
`parser.parseBundle(newTypes);`
`parser.parseResources(newResources);`
however "_parser.parseResources()_" does not exist as a function.

I believe it should be instead:
`// Create a parser and parse it using the parser`
`var parser = new ParseConformance(false, FhirVersions.STU3);           // don't load pre-parsed data`
`parser.parseBundle(newValueSets);`
`parser.parseBundle(newTypes);`
`parser.parseBundle(newResources);`

**Comment by seanmcilvenna** [comment]
Thanks for pointing this out!
