### ISSUE TITLE
Parser not working properly for QuestionnaireResponse objects.

### ISSUE THREAD

**Issue by rjdsilv** [lantanagroup/FHIR.js#7]
When trying to convert a Bundle with QuestionnaireResponse object inside of it, the conversion is not properly made, besides the fact that the validate method is saying that the XML file is valid. The problem happens when QuestionnaireResponse/item has an array of items inside it (which is described in FHIR API). The inner items are converted to empty arrays.

[QuestionnaireResponse_01.zip](https://github.com/lantanagroup/FHIR.js/files/1984659/QuestionnaireResponse_01.zip)

I am attaching both files (the original xml and the parsed json).

Thanks.

**Comment by seanmcilvenna** [comment]
Thanks for the info @rjdsilv. I will try to take a look at this over the next couple days. I will probably load your examples into a unit test and make the unit test work.

**Comment by seanmcilvenna** [comment]
Can you confirm what is in the sample files you sent?
Is the JSON the file you attempted to have FHIR.js convert?
If so, is the XML file the one that FHIR.js produced? Or is it from another system?

**Comment by seanmcilvenna** [comment]
I just did published version 4.1.1 to npm which should address this issue. I have added a couple unit tests to ensure that QuestionnaireResponse.item (and ".item" and ".item.item", etc.) is properly serialized between JSON and XML.
